name: Deploy Docker Image

on:
  push:
    branches: ["main", "docker"]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Set environment variables for next build
        run: |
          cat << EOF >> $GITHUB_ENV
          BASE_URL=${{ secrets.BASE_URL }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          USERNAME=${{ secrets.USERNAME }}
          PASSWORD=${{ secrets.PASSWORD }}
          EMAIL=${{ secrets.EMAIL }}
          WIDGET_STORE=${{ vars.WIDGET_STORE }}
          UPSTASH_ENDPOINT=${{ secrets.UPSTASH_ENDPOINT }}
          UPSTASH_TOKEN=${{ secrets.UPSTASH_TOKEN }}
          EOF
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v8,linux/arm64/v8
          push: true
          tags: cuvar/panal:latest
