name: Deploy Docker Image

on:
  push:
    branches: ["main", "docker"]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Write stub environment variables to .env file
        uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          input-prefix: "ENV_KEY_"
        env:
          ENV_KEY_NEXTAUTH_URL: "http://localhost:3000"
          ENV_KEY_NEXTAUTH_SECRET: "secret"
          ENV_KEY_USERNAME: "username"
          ENV_KEY_PASSWORD: "password"
          ENV_KEY_EMAIL: "build@pipeline.de"
          ENV_KEY_WIDGET_STORE: file
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v8,linux/arm64/v8
          push: true
          tags: ncrypted1504/panal:latest
