name: License Checker

on:
  pull_request:
    branches: ["main"]

jobs:
  license-checker:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      EMAIL: ${{ secrets.EMAIL }}
      WIDGET_STORE: ${{ vars.WIDGET_STORE }}
      UPSTASH_ENDPOINT: ${{ secrets.UPSTASH_ENDPOINT }}
      UPSTASH_TOKEN: ${{ secrets.UPSTASH_TOKEN }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"
      - run: npm install -g license-checker
      - run: npm run check-license
