name: Testing

on:
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash
    working-directory: ./web

jobs:
  test:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      EMAIL: ${{ secrets.EMAIL }}
      WIDGET_STORE: ${{ vars.WIDGET_STORE }}
      UPSTASH_ENDPOINT: ${{ secrets.UPSTASH_ENDPOINT }}
      UPSTASH_TOKEN: ${{ secrets.UPSTASH_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"
      - run: npm ci
      - run: npm test
